yon_memories/config/routes.rb
Rails.application.routes.draw do
  resources :memories
  root 'memories#index'

end

yon_memories/app/models/memory.rb
class Memory < ActiveRecord::Base
	has_attached_file :photo, styles: { medium: "300x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

yon_memories/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

yon_memories/app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_memory, only: [:show, :edit, :update, :destroy]

  # GET /memories
  # GET /memories.json
  def index
    @memories = Memory.all
  end

  # GET /memories/1
  # GET /memories/1.json
  def show
  end

  # GET /memories/new
  def new
    @memory = Memory.new
  end

  # GET /memories/1/edit
  def edit
  end

  # POST /memories
  # POST /memories.json
  def create
    @memory = Memory.new(memory_params)

    respond_to do |format|
      if @memory.save
        format.html { redirect_to @memory, notice: 'Memory was successfully created.' }
        format.json { render :show, status: :created, location: @memory }
      else
        format.html { render :new }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memories/1
  # PATCH/PUT /memories/1.json
  def update
    respond_to do |format|
      if @memory.update(memory_params)
        format.html { redirect_to @memory, notice: 'Memory was successfully updated.' }
        format.json { render :show, status: :ok, location: @memory }
      else
        format.html { render :edit }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memories/1
  # DELETE /memories/1.json
  def destroy
    @memory.destroy
    respond_to do |format|
      format.html { redirect_to memories_url, notice: 'Memory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memory
      @memory = Memory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memory_params
      params.require(:memory).permit(:name, :story, :photo)
    end
end

yon_memories/app/helpers/application_helper.rb
module ApplicationHelper
end

yon_memories/app/helpers/memories_helper.rb
module MemoriesHelper
end

yon_memories/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YonMemories</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="app">
	<%= yield %>
</div>


</body>
</html>

yon_memories/app/views/memories/_form.html.erb
<%= form_for @memory, url: memories_path, html: { multipart: true, class: 'form-style-1' } do |f| %>
  <% if @memory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memory.errors.count, "error") %> prohibited this memory from being saved:</h2>

      <ul>
      <% @memory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "השם שלך" %><br>
    <%= f.text_field :name, class: 'field-long' %>
  </div>
  <div class="field">
    <%= f.label :story, "הזכרון שלך" %><br>
    <%= f.text_area :story, class: 'field-long field-textarea' %>
  </div>

  <div class="field">
    <%= f.label :photo, "תמונה שלך עם יונת?"%><br>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit "פרסם את הזיכרון" %>
  </div>
<% end %>

yon_memories/app/views/memories/edit.html.erb
<h1>Editing Memory</h1>

<%= render 'form' %>

<%= link_to 'Show', @memory %> |
<%= link_to 'Back', memories_path %>

yon_memories/app/views/memories/index.html.erb
<script type="text/javascript">
   var memories_count = <%= @memories.count %>;

   $( document ).ready(function() {
      init(memories_count);
   });
   
</script>

<p id="notice"><%= notice %></p>

<div id="title">
  רגעים עם יונת 
</div>

<div id="memories-container">
  <% @memories.each do |memory| %>
    <div class="memory">
      <div class="image-container">
        <%= image_tag memory.photo.url(:medium) %>
      </div>
      

      <div class="story-container">
        <div class="name"><%= memory.name %></div>
        <div class="story">
          <%= memory.story %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div id="actions-container">
  <a id="stop" class='ph-button ph-btn-red'>עצור</a>
  <a id="continue" class='ph-button ph-btn-green'>המשך</a>
  <div id="new-memory">
    <%= link_to 'העלה זיכרון משלך', new_memory_path, class: 'ph-button ph-btn-blue' %>
  </div>
</div>

yon_memories/app/views/memories/new.html.erb
<div id="new-memory">
	<h1>מה הזיכרון שלך?</h1>

	<%= render 'form' %>

	<%= link_to 'Back', memories_path %>
</div>

yon_memories/app/views/memories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @memory.name %>
</p>

<p>
  <strong>Story:</strong>
  <%= @memory.story %>
</p>

<p>
	<strong>Photo:</strong>
	<%= image_tag @memory.photo.url(:medium) %>
</p>

<%= link_to 'Edit', edit_memory_path(@memory) %> |
<%= link_to 'Back', memories_path %>